# Generated by Django 4.0 on 2022-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='image',
            field=models.ImageField(default=0, upload_to='medicines', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
