# Generated by Django 4.0 on 2022-09-29 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_medicament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='expr_date',
            field=models.CharField(max_length=10, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='manu_date',
            field=models.CharField(max_length=10, verbose_name='Date of manufacture'),
        ),
    ]
