# Generated by Django 4.0 on 2022-09-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0003_medicament_create_alter_medicament_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='image',
            new_name='picture',
        ),
    ]
