# Generated by Django 4.0 on 2022-10-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0004_rename_image_medicament_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='expr_date',
            field=models.DateField(max_length=10, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='manu_date',
            field=models.DateField(max_length=10, verbose_name='Date of manufacture'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='medicines', verbose_name='Image'),
        ),
    ]
