# Generated by Django 4.0 on 2022-08-29 04:49

import compte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone_number')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=compte.models.user_directory_path, verbose_name='Picture')),
                ('user_type', models.CharField(choices=[('PHARMACIST', 'pharmacist'), ('VIGILE', 'vigile'), ('ADMIN', 'admin')], default='pharmacist', max_length=100, verbose_name='User Type')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superadmin')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
