# Generated by Django 4.0 on 2022-09-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_account_birth_date_alter_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birth Date'),
        ),
    ]
